export const KEYWORDS = {
	Type: "Class",
	DerivedFrom: "Inheritance",
	TrueFor: "TrueFor",
	Else: "Else",
	Ity: "Integer",
	Sity: "SInteger",
	Cwq: "Character",
	CwqSequence: "String",
	Ifity: "Float",
	Sifity: "SFloat",
	Valueless: "Void",
	Logical: "Boolean",
	Endthis: "Break",
	However: "Loop",
	When: "Loop",
	Respondwith: "Return",
	Srap: "Struct",
	Scan: "Switch",
	Conditionof: "Switch",
	Require: "Inclusion",
};

export const SYMBOLS = {
	"@": "Start Symbol",
	"^": "Start Symbol",
	$: "End Symbol",
	"#": "End Symbol",
	"+": "Arithmetic Operation",
	"-": "Arithmetic Operation",
	"*": "Arithmetic Operation",
	"/": "Arithmetic Operation",
	"&&": "Logic operator",
	"||": "Logic operator",
	"~": "Logic operator",
	"==": "Relational operator",
	"!=": "Relational operator",
	">": "Relational operator",
	"<": "Relational operator",
	">=": "Relational operator",
	"<=": "Relational operator",
	"=": "Assignment operator",
	"->": "Access Operator",
	"{": "Left Curly Braces",
	"}": "Right Curly Braces",
	"(": "Left Parenthesis",
	")": "Right Parenthesis",
	"[": "Left Square Bracket",
	"]": "Right Square Bracket",
	";": "Semicolon",
	",": "Comma",
	'"': "Double Quotation Mark",
	"'": "Single Quotation Mark",
};
